config/routes.rb
Codewatch::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  root to: 'home#index'

  get 'dashboard' => 'dashboard#index', as: :user_dashboard
  get 'dashboard/chat_management' => 'dashboard#chat_management', as: :user_dashboard_chat_management
  get 'dashboard/statistics' => 'dashboard#statistics', as: :user_dashboard_statistics
  get 'dashboard/stream_keys' => 'dashboard#stream_keys', as: :user_dashboard_stream_keys

  get 'dashboard/private_sessions' => 'dashboard#private_sessions', as: :user_dashboard_private_sessions
  post 'dashboard/private_sessions/create' => 'dashboard#create_private_session', as: :user_dashboard_private_sessions_create
  get 'dashboard/private_sessions/:id/edit' => 'dashboard#edit_private_session', as: :user_dashboard_private_sessions_edit
  post 'dashboard/private_sessions/:id/update' => 'dashboard#update_private_session', as: :user_dashboard_private_sessions_update
  put 'dashboard/private_sessions/:id/cancel' => 'dashboard#cancel_private_session', as: :user_dashboard_private_sessions_cancel

  get 'dashboard/subscriptions' => 'dashboard#subscriptions', as: :user_dashboard_subscriptions
  put 'dashboard/subscription/plus/:id/cancel' => 'dashboard#cancel_plus_subscription', as: :user_dashboard_plus_subscription_cancel
  put 'dashboard/subscription/channel/:id/cancel' => 'dashboard#cancel_channel_subscription', as: :user_dashboard_channel_subscription_cancel

  match 'edit/channel' => 'dashboard#edit_channel', as: :edit_user_channel, via: [ :get, :post, :delete ]

  post 'dashboard/update_user' => 'dashboard#update_user', as: :update_user
  post 'dashboard/update_settings' => 'dashboard#update_settings', as: :update_settings
  post 'dashboard/update_password' => 'dashboard#update_password', as: :update_password

  get 'dashboard/vod/delete/:id' => 'dashboard#delete_vod', as: :delete_vod
  get 'dashboard/vod/toggle_visibility/:id' => 'dashboard#show_hide_vod', as: :toggle_vod_visibility

  get 'channel/:username' => 'channel#show', as: :user_channel

  get 'categories/:category_name' => 'categories#show', as: :category_channels

  get 'categories' => 'categories#index', as: :categories

  get 'search' => 'search#search', as: :search

  get 'vod/:username' => 'vod#index', as: :list_vod
  get 'vod/:username/:recording_id' => 'vod#show', as: :show_vod

  get 'events' => 'events#index', as: :events

  get 'help' => 'help#index', as: :help

  get 'channels/external' => 'external_streams#index', as: :external_channels
  get 'channel/external/:username' => 'external_streams#show', as: :user_external_channel

  get 'private_session/:id' => 'private_sessions#show', as: :private_session

  get 'payments/plus' => 'payments#new_plus', as: :new_plus_payment
  resources :payments
  get 'payments/private-session/:id' => 'payments#new_private_session', as: :new_private_session_payment
  get 'payments/plus/success' => 'payments#plus_success', as: :plus_success_payment
  get 'payments/channel_subscription/:id' => 'payments#new_channel_subscription', as: :channel_subscription_payment
  get 'payments/channel_subscription/:id/success' => 'payments#channel_subscription_success', as: :channel_subscription_success_payment

  get 'terms' => 'terms#show', as: :terms
  get 'privacy' => 'privacy#show', as: :privacy
  get 'about' => 'about#show', as: :about

  match '404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]

  post 'chat/:chat_id/new_message' => 'chat#new_message'
  namespace :api do
    namespace :v1 do
      resource :auth, defaults: {format: 'json'} do
        post 'stream' => 'auth#stream', defaults: {format: 'json'}
      end
      resource :smil, defaults: {format: 'text'} do
        get ':username' => 'smil#generate', defaults: {format: 'text'}
      end
      resource :stream, defaults: {format: 'json'} do
        post 'new_recording' => 'stream#new_recording', defaults: {format: 'json'}
        post 'event/:event' => 'stream#event', defaults: {format: 'json'}
      end
      resource :recording, defaults: {format: 'json'} do
        post 'event/:event' => 'recording#event', defaults: {format: 'json'}
      end
      resource :chat, defaults: {format: 'json'} do
        put ':channel_id/toggle_moderator/:username' => 'chat#toggle_moderator', defaults: {format: 'json'}, as: :chat_toggle_moderator
        put ':channel_id/ban/:username' => 'chat#ban', defaults: {format: 'json'}, as: :chat_ban
        put ':channel_id/unban/:username' => 'chat#unban', defaults: {format: 'json'}, as: :chat_unban
        delete ':channel_id/user/:username/delete/:message_id' => 'chat#remove_message', defaults: {format: 'json'}, as: :chat_remove_message
      end
      resource :private_session, defaults: {format: 'json'} do
        delete ':id/delete' => 'chat#toggle_moderator', defaults: {format: 'json'}, as: :delete
      end
      resource :channel, defaults: {format: 'json'} do
        post ':channel_id/like' => 'channel#like', defaults: {format: 'json'}, as: :channel_like
        delete ':channel_id/unlike' => 'channel#unlike', defaults: {format: 'json'}, as: :channel_unlike
      end
      resource :load_balancer, defaults: {format: 'json'} do
        post 'node' => 'load_balancer#stream', defaults: {format: 'json'}, as: :node
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  attr_reader :private_session
  attr_reader :stream_keys

  add_breadcrumb 'Dashboard', :user_dashboard_path

  helper_method :channel
  helper_method :private_session
  helper_method :timezone_to_offset
  helper_method :stream_keys

  def index
    add_breadcrumb 'Profile', :user_dashboard_path
    @user = current_user
  end

  def edit_channel
    if request.post?
      category = Category.where(name: params['channel']['category']).first
      if category
        current_user.channel.update_attributes(category: category, title: params['channel']['title'], description: params['channel']['description'])
        flash[:notice] = 'Channel updated'
      else
        flash[:alert] = 'Cannot find that category'
      end
      redirect_to edit_user_channel_path
    end
  end

  def chat_management
    add_breadcrumb 'Chat Management', :user_dashboard_chat_management_path
    @banned_users = current_user.channel.chat.users_banned
    @moderator_users = current_user.channel.chat.users_moderator
  end

  def stream_keys
    private_session_stream_keys = current_user.private_sessions.inject({}) do |res, ps|
      res[ps.title] = {key: ps.token, private_key: ps.stream_key}
      res
    end
    @stream_keys = {
        'Current Stream Key' => {key: current_user.username, private_key: current_user.stream_key}
    }.merge(private_session_stream_keys)
  end

  def update_user
    @user = User.find(current_user.id)

    if @user.update(user_params)
      flash[:notice] = 'User updated'
    else
      user_input_error
    end

    redirect_to user_dashboard_path
  end

  def update_settings
    @user = User.find(current_user.id)

    record_stream = params[:user] && params[:user][:record_stream] ? 1 : 0

    if @user.update(record_stream: record_stream)
      flash[:notice] = 'Settings updated'
    else
      user_input_error
    end

    redirect_to user_dashboard_path
  end

  def update_password
    @user = User.find(current_user.id)

    if @user.update_with_password(user_params) && !params[:user][:password].blank?
      flash[:notice] = "Password updated."
      # Sign in the user by passing validation in case their password changed
      sign_in @user, :bypass => true
    else
      @user.errors[:password] << t('errors.messages.blank') if params[:user][:password].blank?
      user_input_error
    end

    redirect_to user_dashboard_path
  end

  def show_hide_vod
    @recording = Recording.find(params[:id])

    if @recording
      @recording.toggle_visibility
      flash[:notice] = 'VoD hidden successfully'
    else
      flash[:alert] = 'Cannot find that VoD'
    end

    redirect_to user_dashboard_path
  end

  def delete_vod
    @recording = Recording.find(params[:id])

    if @recording
      @recording.delete
      flash[:notice] = 'VoD deleted successfully'
    else
      flash[:alert] = 'Cannot find that VoD'
    end

    redirect_to user_dashboard_path
  end

  def private_sessions
    @private_sessions = current_user.private_sessions
  end

  def create_private_session
    begin
      if current_user.permissions.can_create_private_sessions?
        live_at = DateTime.new(
            params['private_session']['live_at_year'].to_i,
            params['private_session']['live_at_month'].to_i,
            params['private_session']['live_at_day'].to_i,
            params['private_session']['live_at_hour'].to_i,
            params['private_session']['live_at_minute'].to_i,
            0,
            timezone_to_offset(params['private_session']['live_at_tz']))

        PrivateSession.create!(
            user: current_user,
            title: params['private_session']['title'],
            live_at: live_at,
            max_participants: params['private_session']['max_participants'],
            description: params['private_session']['description'],
            timezone: params['private_session']['live_at_tz'],
            price: params['private_session']['price'].to_f)

        flash[:notice] = 'Private session created successfully'
        redirect_to new_plus_payment_path
      else
        flash[:alert] = 'You need a plus subscription to create private sessions'
        redirect_to user_dashboard_private_sessions_path
      end
    rescue ArgumentError => e
      flash[:alert] = 'Go live date is Invalid'
    rescue Mongoid::Errors::Validations => e
      flash[:alert] = 'Go live date is cannot be in the past'
    end
    redirect_to user_dashboard_private_sessions_path
  end

  def edit_private_session
    @private_session = PrivateSession.where(user: current_user, token: params[:id]).first
  end

  def update_private_session
    private_session = PrivateSession.where(user: current_user, token: params[:id]).first
    if private_session
      begin
        live_at = DateTime.new(
            params['private_session']['live_at_year'].to_i,
            params['private_session']['live_at_month'].to_i,
            params['private_session']['live_at_day'].to_i,
            params['private_session']['live_at_hour'].to_i,
            params['private_session']['live_at_minute'].to_i,
            0,
            timezone_to_offset(params['private_session']['live_at_tz']))

        private_session.update!(
            title: params['private_session']['title'],
            live_at: live_at,
            max_participants: params['private_session']['max_participants'],
            description: params['private_session']['description'],
            timezone: params['private_session']['live_at_tz'],
            price: params['private_session']['price'].to_f)

        flash[:notice] = 'Private session changed successfully'
        redirect_to user_dashboard_private_sessions_path
      rescue ArgumentError => e
        flash[:alert] = 'Go live date is Invalid'
        redirect_to user_dashboard_private_sessions_edit_path(private_session.id)
      rescue Mongoid::Errors::Validations => e
        flash[:alert] = 'Go live date is cannot be in the past'
        redirect_to user_dashboard_private_sessions_edit_path(private_session.id)
      end
    else
      flash[:error] = 'Could not find session'
      redirect_to user_dashboard_private_sessions_path
    end
  end

  def cancel_private_session
    private_session = PrivateSession.where(user: current_user, token: params[:id]).first
    if private_session
      private_session.update(status: :cancelled)
      flash[:notice] = 'Cancelled successfully'
    else
      flash[:error] = 'Could not find session'
    end
    redirect_to user_dashboard_private_sessions_path
  end

  def subscriptions
    @plus_subscriptions = current_user.plus_subscriptions
    @channel_subscriptions = current_user.channel_subscriptions
  end

  def cancel_plus_subscription
    redirect_to user_dashboard_private_sessions_path
    if UserService.instance.cancel_plus_subscription(current_user, params[:id])
      flash[:notice] = 'Cancelled successfully.'
    else
      flash[:error] = 'There was an error while trying to cancel you subscription.'
    end
    redirect_to user_dashboard_private_sessions_path
  end

  def cancel_channel_subscription
    if ChannelService.instance.cancel_subscription(current_user, params[:id])
      flash[:notice] = 'Cancelled successfully.'
    else
      flash[:error] = 'There was an error while trying to cancel you subscription.'
    end
    redirect_to user_dashboard_private_sessions_path
  end

  def channel
    current_user.channel
  end

  private

  def timezone_to_offset(string)
    ActiveSupport::TimeZone.all.find { |tz| tz.to_s == string }.formatted_offset
  end

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.required(:user).permit(:email, :username, :current_password, :password,
                                  :password_confirmation, :timezone, :occupation, :first_name, :last_name,
                                  :facebook_link, :twitter_link, :github_link, :google_plus_link)
  end

  def user_input_error
    flash[:alert] = @user.errors.full_messages.first
  end

  def page_options
    super.merge({page_id: 'dashboard'})
  end
end

app/views/dashboard/_can_create_private_session.html.haml
.dashboard-body.margin-bottom-20
  .tab-v1
    %ul.nav.nav-justified.nav-tabs
      %li.active
        %a{'data-toggle' => 'tab', :href => '#private-sessions-tab'} Your Private Sessions
      %li
        %a{'data-toggle' => 'tab', :href => '#new-private-session-tab'} Create Private Session
    .tab-content
      #private-sessions-tab.dashboard-edit.tab-pane.fade.in.active
        %h2.heading-md Manage your private sessions
        %p Below you can change and delete your private sessions
        .row
          .col-md-12
            .panel.margin-bottom-40
              .panel-heading
                %h3.panel-title
                  %i.fa.fa-user
                  Private sessions (#{@private_sessions.count})
              .panel-body
                %table.table.table-hover
                  %thead
                    %tr
                      %th Title
                      %th Status
                      %th Live date
                      %th Signups
                      %th
                  %tbody
                    - @private_sessions.each_with_index do |private_session, i|
                      %tr
                        %td= private_session.title
                        %td= private_session.status.capitalize
                        %td
                          = private_session.live_at.to_formatted_s(:long_ordinal)
                          %br
                          = private_session.timezone
                        %td= private_session.participants.count
                        %td
                          .row
                            .col-md-5
                              = button_to user_dashboard_private_sessions_edit_path(private_session.token), {form_class: 'form-unban-user', class: 'btn btn-warning btn-xs edit-private-session', method: :get} do
                                %i.fa.fa-edit
                                Edit
                            .col-md-5
                              = button_to user_dashboard_private_sessions_cancel_path(private_session.token), {form_class: 'form-unban-user', class: 'btn btn-danger btn-xs delete-private-session', method: :put} do
                                %i.fa.fa-trash-o
                                Cancel
                          .row.margin-top-15
                            .col-md-8
                              = button_to user_dashboard_stream_keys_path, {form_class: 'form-unban-user', class: 'btn btn-success btn-xs private-session-stream-key', method: :get} do
                                %i.fa.fa-key
                                Stream Key
                            .col-md-4
                              = button_to private_session_path(private_session.token), {form_class: 'form-unban-user', class: 'btn btn-info btn-xs private-session-link', method: :get} do
                                %i.fa.fa-link
                                Link

      #new-private-session-tab.dashboard-edit.tab-pane.fade
        %h2.heading-md Create a new Private Session
        %p Fill the information below to create a new private session.
        %br
          = form_tag(user_dashboard_private_sessions_create_path, {id: 'sky-form4', class: 'sky-form'}) do
            %dl.dl-horizontal
              %dt Title
              %dd
                %section
                  %label.input
                    %i.icon-append.fa.fa-font
                    %input{:name => "private_session[title]", :placeholder => "Title", :type => "text"}
                      %b.tooltip.tooltip-bottom-right The title for your private session
              %dt Live date
              %dd.with-col
                %section.col.col-3.day
                  %label.select
                    %select{:name => "private_session[live_at_day]"}
                      %option{value: '0', selected: true, disabled: true} Day
                      - (1..31).each do |day|
                        %option{value: day}= day.to_i.ordinalize
                    %i
                %section.col.col-3.month
                  %label.select
                    %select{:name => "private_session[live_at_month]"}
                      %option{value: '0', selected: true, disabled: true} Month
                      - (1..12).each do |month|
                        %option{value: month}= Date::MONTHNAMES[month]
                    %i
                %section.col.col-3.year
                  %label.select
                    %select{:name => "private_session[live_at_year]"}
                      %option{value: '0', selected: true, disabled: true} Year
                      - [DateTime.now.year, DateTime.now.year+1].each do |year|
                        %option{value: year}= year
                    %i
                %section.col.col-3.hour
                  %label.select
                    %select{:name => "private_session[live_at_hour]"}
                      %option{value: '0', selected: true, disabled: true} Hour
                      - (0..23).each do |hour|
                        %option{value: hour}= sprintf '%02d', hour
                    %i
                %section.col.col-3.minute
                  %label.select
                    %select{:name => "private_session[live_at_minute]"}
                      %option{value: '0', selected: true, disabled: true} Minute
                      - (0..59).each do |minute|
                        %option{value: minute}= sprintf '%02d', minute
                    %i
                %section.col.col-6.minute
                  %label.select
                    %select{:name => "private_session[live_at_tz]"}
                      %option{value: '0', selected: true, disabled: true} Timezone
                      - ActiveSupport::TimeZone.all.each do |tz|
                        %option{value: tz}= tz
                    %i
              %dt Max participants
              %dd.with-col
                %section.col.col-3
                  %label.input
                    %i.icon-append.fa.fa-users
                    %input{:name => "private_session[max_participants]", :placeholder => "Unlimited: 0", :type => "text", :value => '0'}
                      %b.tooltip.tooltip-bottom-right Unlimited: 0
              %dt Price
              %dd.with-col
                %section.col.col-3
                  %label.input
                    %i.icon-append.fa.fa-dollar
                    %input{:name => "private_session[price]", :placeholder => "Free: 0", :type => "text"}
                      %b.tooltip.tooltip-bottom-right Leave at 0 for Free
              %dt.margin-bottom-20 Description
              %dd &nbsp;
              %dd{style: 'margin-left: 0;'}
                %section
                  %textarea{class: 'form-control tinymce', id: 'private-session-description', name: 'private_session[description]', rows: '15'}
                  = tinymce
            %br
              %button.btn-u{:type => "submit"} Create

app/views/dashboard/_can_not_create_private_session.html.haml
.dashboard-body.margin-bottom-20
  .tab-v1
    .tab-content
      #statistics-tab.dashboard-edit.tab-pane.fade.in.active
        %h2.heading-md Reserved for plus subscribers
        %p In order to get access to this funcitonality you'll require a plus subscription
        %br
        .row.margin-top-30.margin-bottom-50
          .col.col-md-5
            = link_to new_plus_payment_path do
              %button#payment-button.btn-u.btn-u-lg.btn-block{:type => 'button'}= "What's a Plus subscription?"

app/views/dashboard/_navigation.html.haml
%ul#sidebar-nav-1.list-group.sidebar-nav-v1.margin-bottom-40
  %li.list-group-item{class: params[:action] == 'index' ? 'active' : ''}
    = link_to user_dashboard_path do
      %i.fa.fa-user
      Profile
  %li.list-group-item{class: params[:action] == 'subscriptions' ? 'active' : ''}
    = link_to user_dashboard_subscriptions_path do
      %i.fa.fa-user-plus
      Subscriptions
  %li.list-group-item{class: params[:action] == 'stream_keys' ? 'active' : ''}
    = link_to user_dashboard_stream_keys_path do
      %i.fa.fa-key
      Stream Keys
  %li.list-group-item{class: params[:action] == 'statistics' ? 'active' : ''}
    = link_to user_dashboard_statistics_path do
      %i.fa.fa-bar-chart-o
      Statistics
  %li.list-group-item{class: params[:action] == 'private_sessions' ? 'active' : ''}
    = link_to user_dashboard_private_sessions_path do
      %i.fa.fa-users
      Private Sessions
  %li.list-group-item{class: params[:action] == 'chat_management' ? 'active' : ''}
    = link_to user_dashboard_chat_management_path do
      %i.fa.fa-comments-o
      Channel Management

app/views/dashboard/_portrait.html.haml
%img.img-responsive.dashboard-img.margin-bottom-20{:alt => "", :src => current_user.gravatar_url}

app/views/dashboard/index.html.haml
= render partial: 'shared/breadcrumbs', locals: {page_name: 'Profile'}
.container.content.dashboard
  .row
    .col-md-3.md-margin-bottom-40
      = render partial: 'dashboard/portrait'
      = render partial: 'dashboard/navigation'
    .col-md-9
      .dashboard-body.margin-bottom-20
        .tab-v1
          %ul.nav.nav-justified.nav-tabs
            %li.active
              %a{"data-toggle" => "tab", :href => "#profile-tab"} Edit Profile
            %li
              %a{"data-toggle" => "tab", :href => "#settings-tab"} Settings
            %li
              %a{"data-toggle" => "tab", :href => "#security-tab"} Security
            %li
              %a{"data-toggle" => "tab", :href => "#vod-tab"} VoD
          .tab-content
            #profile-tab.dashboard-edit.tab-pane.fade.in.active
              %h2.heading-md Manage your Name, ID and Email Addresses.
              %p Below are the name, email address and other information about your account.
              %br
                = form_tag({controller: :dashboard, action: :update_user}, {id: 'sky-form4', class: 'sky-form'}) do
                  %dl.dl-horizontal
                    %dt Username
                    %dd
                      .row
                        %section.col.col-8
                          %label.input
                            %i.icon-append.fa.fa-user
                            %input{:name => "user[username]", :placeholder => "Username", :type => "text", :value => current_user.username}
                              %b.tooltip.tooltip-bottom-right Needed to enter the website
                    %dt Email address
                    %dd
                      .row
                        %section.col.col-8
                          %label.input
                            %i.icon-append.fa.fa-envelope
                            %input{:name => "user[email]", :placeholder => "Email address", :type => "text", :value => current_user.email}
                              %b.tooltip.tooltip-bottom-right Needed to verify your account
                    %dt Your name
                    %dd
                      .row
                        %section.col.col-6
                          %label.input
                            %i.icon-append.fa.fa-user
                            %input{:name => "user[first_name]", :placeholder => "First name", :type => "text", :value => current_user.first_name}
                              %b.tooltip.tooltip-bottom-right Your first name
                        %section.col.col-6
                          %label.input
                            %i.icon-append.fa.fa-user
                            %input{:name => "user[last_name]", :placeholder => "Last name", :type => "text", :value => current_user.last_name}
                              %b.tooltip.tooltip-bottom-right Your last name
                    %dt Occupation
                    %dd
                      %section
                        %label.input
                          %i.icon-append.fa.fa-briefcase
                          %input{:name => "user[occupation]", :placeholder => "Occupation / Job title", :type => "text", :value => current_user.occupation}
                            %b.tooltip.tooltip-bottom-right What's your job title
                    %dt Social
                    %dd
                      .row
                        %section.col.col-6
                          %label.input
                            %i.icon-append.fa.fa-facebook
                            %input{:name => "user[facebook_link]", :placeholder => "Facebook", :type => "text", :value => current_user.facebook_link}
                              %b.tooltip.tooltip-bottom-right Facebook username
                        %section.col.col-6
                          %label.input
                            %i.icon-append.fa.fa-github
                            %input{:name => "user[github_link]", :placeholder => "Github", :type => "text", :value => current_user.github_link}
                              %b.tooltip.tooltip-bottom-right Github username
                      .row
                        %section.col.col-6
                          %label.input
                            %i.icon-append.fa.fa-twitter
                            %input{:name => "user[twitter_link]", :placeholder => "Twitter", :type => "text", :value => current_user.twitter_link}
                              %b.tooltip.tooltip-bottom-right Twitter username
                        %section.col.col-6
                          %label.input
                            %i.icon-append.fa.fa-google-plus
                            %input{:name => "user[google_plus_link]", :placeholder => "Google Plus", :type => "text", :value => current_user.google_plus_link}
                              %b.tooltip.tooltip-bottom-right Google plus username
                    %dt Timezone
                    %dd
                      .row
                        %section.col.col-6
                          %label.select
                            %select{:name => "user[timezone]"}
                              %option{value: '0', selected: true, disabled: true} Timezone
                              - ActiveSupport::TimeZone.all.each do |tz|
                                %option{value: tz, selected: current_user.timezone == tz.to_s}= tz
                            %i
                  %br
                    %button.btn-u.btn-u-default{:type => "button"} Cancel
                    %button.btn-u{:type => "submit"} Save Changes
            #settings-tab.dashboard-edit.tab-pane.fade
              %h2.heading-md Manage your Account Settings
              %p Bellow you can change your account related settings.
              %br
                = form_tag({controller: :dashboard, action: :update_settings}, {id: 'sky-form3', class: 'sky-form'}) do
                  %label.toggle
                    %input{:checked => current_user.record_stream? ? true : false, :name => "user[record_stream]", :type => "checkbox"}
                      %i>
                      Keep recordings (only for Plus subscribers)
                  %hr
                  %br
                    %button.btn-u.btn-u-default{:type => "button"} Cancel
                    %button.btn-u{:type => "submit"} Save Changes
            #security-tab.dashboard-edit.tab-pane.fade
              %h2.heading-md Manage your Security Settings
              %p Bellow you can change your security related settings.
              %br
                = form_tag({controller: :dashboard, action: :update_user}, {id: 'sky-form4', class: 'sky-form'}) do
                  %dl.dl-horizontal
                    %dt Current Password
                    %dd
                      %section
                        %label.input
                          %i.icon-append.fa.fa-lock
                          %input{:name => "user[current_password]", :type => "password", placeholder: 'Your old password here'}
                    %dt New Password
                    %dd
                      %section
                        %label.input
                          %i.icon-append.fa.fa-lock
                          %input{:name => "user[password]", :type => "password", placeholder: 'Your new password here'}
                    %dt Confirm New Password
                    %dd
                      %section
                        %label.input
                          %i.icon-append.fa.fa-lock
                          %input{:name => "user[password_confirmation]", :type => "password", placeholder: 'Confirm your new one, just to be sure :)'}
                  %br
                    %button.btn-u.btn-u-default{:type => "button"} Cancel
                    %button.btn-u{:type => "submit"} Save Changes
            / End Checkout-Form
            #vod-tab.dashboard-edit.tab-pane.fade
              %h2.heading-md Manage your Video on Demand.
              %p Bellow you can manage your videos on demand.
              %br
                - current_user.recordings.order_by(created_at: :desc).each do |recording|
                  .media
                    .media-left
                      %a{href: show_vod_path(recording.user.username, recording.id)}
                        = image_tag "https://codewatch-tv.s3-eu-west-1.amazonaws.com/recording-thumbnails/#{recording.name.gsub('.flv', '')}.png", height: 72
                    .media-body
                      %h4.media-heading= recording.title
                      %h5 Created at #{recording.created_at}
                      %p
                        %i.fa.fa-eye
                          = recording.views
                    .media-right
                      = link_to toggle_vod_visibility_path(recording.id), class: 'margin-bottom-5' do
                        - if recording.is_visible?
                          %i.fa.fa-eye-slash &nbsp;Hide
                        - else
                          %i.fa.fa-eye &nbsp;Show
                      = link_to delete_vod_path(recording.id) do
                        %i.fa.fa-trash &nbsp;Delete

app/views/dashboard/private_sessions.html.haml
= render partial: 'shared/breadcrumbs', locals: {page_name: 'Profile'}
.container.content.dashboard
  .row
    .col-md-3.md-margin-bottom-40
      = render partial: 'dashboard/portrait'
      = render partial: 'dashboard/navigation'
    .col-md-9
      - if current_user.permissions.can_create_private_sessions?
        = render 'can_create_private_session'
      - else
        = render 'can_not_create_private_session'