config/routes.rb
Codewatch::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  root to: 'home#index'

  get 'dashboard' => 'dashboard#index', as: :user_dashboard
  get 'dashboard/chat_management' => 'dashboard#chat_management', as: :user_dashboard_chat_management
  get 'dashboard/statistics' => 'dashboard#statistics', as: :user_dashboard_statistics
  get 'dashboard/stream_keys' => 'dashboard#stream_keys', as: :user_dashboard_stream_keys

  get 'dashboard/private_sessions' => 'dashboard#private_sessions', as: :user_dashboard_private_sessions
  post 'dashboard/private_sessions/create' => 'dashboard#create_private_session', as: :user_dashboard_private_sessions_create
  get 'dashboard/private_sessions/:id/edit' => 'dashboard#edit_private_session', as: :user_dashboard_private_sessions_edit
  post 'dashboard/private_sessions/:id/update' => 'dashboard#update_private_session', as: :user_dashboard_private_sessions_update
  put 'dashboard/private_sessions/:id/cancel' => 'dashboard#cancel_private_session', as: :user_dashboard_private_sessions_cancel

  get 'dashboard/subscriptions' => 'dashboard#subscriptions', as: :user_dashboard_subscriptions
  put 'dashboard/subscription/plus/:id/cancel' => 'dashboard#cancel_plus_subscription', as: :user_dashboard_plus_subscription_cancel
  put 'dashboard/subscription/channel/:id/cancel' => 'dashboard#cancel_channel_subscription', as: :user_dashboard_channel_subscription_cancel

  match 'edit/channel' => 'dashboard#edit_channel', as: :edit_user_channel, via: [ :get, :post, :delete ]

  post 'dashboard/update_user' => 'dashboard#update_user', as: :update_user
  post 'dashboard/update_settings' => 'dashboard#update_settings', as: :update_settings
  post 'dashboard/update_password' => 'dashboard#update_password', as: :update_password

  get 'dashboard/vod/delete/:id' => 'dashboard#delete_vod', as: :delete_vod
  get 'dashboard/vod/toggle_visibility/:id' => 'dashboard#show_hide_vod', as: :toggle_vod_visibility

  get 'channel/:username' => 'channel#show', as: :user_channel

  get 'categories/:category_name' => 'categories#show', as: :category_channels

  get 'categories' => 'categories#index', as: :categories

  get 'search' => 'search#search', as: :search

  get 'vod/:username' => 'vod#index', as: :list_vod
  get 'vod/:username/:recording_id' => 'vod#show', as: :show_vod

  get 'events' => 'events#index', as: :events

  get 'help' => 'help#index', as: :help

  get 'channels/external' => 'external_streams#index', as: :external_channels
  get 'channel/external/:username' => 'external_streams#show', as: :user_external_channel

  get 'private_session/:id' => 'private_sessions#show', as: :private_session

  get 'payments/plus' => 'payments#new_plus', as: :new_plus_payment
  resources :payments
  get 'payments/private-session/:id' => 'payments#new_private_session', as: :new_private_session_payment
  get 'payments/plus/success' => 'payments#plus_success', as: :plus_success_payment
  get 'payments/channel_subscription/:id' => 'payments#new_channel_subscription', as: :channel_subscription_payment
  get 'payments/channel_subscription/:id/success' => 'payments#channel_subscription_success', as: :channel_subscription_success_payment

  get 'terms' => 'terms#show', as: :terms
  get 'privacy' => 'privacy#show', as: :privacy
  get 'about' => 'about#show', as: :about

  match '404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]

  post 'chat/:chat_id/new_message' => 'chat#new_message'
  namespace :api do
    namespace :v1 do
      resource :auth, defaults: {format: 'json'} do
        post 'stream' => 'auth#stream', defaults: {format: 'json'}
      end
      resource :smil, defaults: {format: 'text'} do
        get ':username' => 'smil#generate', defaults: {format: 'text'}
      end
      resource :stream, defaults: {format: 'json'} do
        post 'new_recording' => 'stream#new_recording', defaults: {format: 'json'}
        post 'event/:event' => 'stream#event', defaults: {format: 'json'}
      end
      resource :recording, defaults: {format: 'json'} do
        post 'event/:event' => 'recording#event', defaults: {format: 'json'}
      end
      resource :chat, defaults: {format: 'json'} do
        put ':channel_id/toggle_moderator/:username' => 'chat#toggle_moderator', defaults: {format: 'json'}, as: :chat_toggle_moderator
        put ':channel_id/ban/:username' => 'chat#ban', defaults: {format: 'json'}, as: :chat_ban
        put ':channel_id/unban/:username' => 'chat#unban', defaults: {format: 'json'}, as: :chat_unban
        delete ':channel_id/user/:username/delete/:message_id' => 'chat#remove_message', defaults: {format: 'json'}, as: :chat_remove_message
      end
      resource :private_session, defaults: {format: 'json'} do
        delete ':id/delete' => 'chat#toggle_moderator', defaults: {format: 'json'}, as: :delete
      end
      resource :channel, defaults: {format: 'json'} do
        post ':channel_id/like' => 'channel#like', defaults: {format: 'json'}, as: :channel_like
        delete ':channel_id/unlike' => 'channel#unlike', defaults: {format: 'json'}, as: :channel_unlike
      end
      resource :load_balancer, defaults: {format: 'json'} do
        post 'node' => 'load_balancer#stream', defaults: {format: 'json'}, as: :node
      end
    end
  end
end

app/views/shared/_breadcrumbs.html.haml
.breadcrumbs
  .container
    %h1.pull-left= page_name
    %ul.pull-right.breadcrumb
      = render_breadcrumbs tag: :li, separator: ''

app/views/shared/_channel_stats.html.haml
#channel-stats
  .row.margin-bottom-20
    .col-sm-6.sm-margin-bottom-20.total-viewers
      .service-block-v3.service-block-u
        %i.fa.fa-eye
        %span.service-heading Views
        %span.counter= total_viewers
    .col-sm-6.current-viewers
      .service-block-v3.service-block-u
        %i.fa.fa-user
        %span.service-heading Viewers
        %span.counter= current_viewers == 0 ? 1 : current_viewers
  .row
    .col-sm-6.sm-margin-bottom-20.likes
      #likes-channel{class: user_likes_channel? ? '' : 'hide' }
        = link_to channel_unlike_api_v1_channel_path(channel.user.username), id: 'ajax-unlike-channel', remote: true, method: :delete  do
          .service-block-v3.service-block-red
            %i.fa.fa-heart
            %span.service-heading Likes
            %span.counter= likes
      #does-not-likes-channel{class: user_likes_channel? ? 'hide' : '' }
        = link_to channel_like_api_v1_channel_path(channel.user.username), id: 'ajax-like-channel', remote: true, method: :post  do
          .service-block-v3.service-block-red
            %i.fa.fa-heart
            %span.service-heading Likes
            %span.counter= likes
    .col-sm-6.vod
      - if is_channel_subscriber?
        .service-block-v3.service-block-yellow
          %i.fa.fa-star
          %span.service-heading Subscribed
          %span.counter Thanks!
      - else
        = link_to channel_subscription_payment_path(channel.user.username) do
          .service-block-v3.service-block-yellow
            %i.fa.fa-user-plus
            %span.service-heading Subscribe
            %span.counter= number_to_currency(BUSINESS_MODEL['prices']['channel_subscription'].to_f)

app/views/shared/_chat.html.haml
.panel.panel-profile
  .panel-heading.overflow-h
    %h2.panel-title.heading-sm.pull-left
      %i.fa.fa-comments-o
      Chat
  #chat-messages.panel-body.no-padding
  .panel-footer
    = form_tag("/chat/#{chat_id}/new_message", :id => 'new_message_form', :remote => true) do
      %input#channel_id{:type => "hidden", :value => "#{chat_id}"}
      .input-group
        - if current_user
          %input#chat-message.btn-input.form-control.input-sm{:placeholder => "Type your message here...", :type => "text", :name => "message"}/
          %span.input-group-btn
            %button#btn-chat.btn.btn-warning.btn-sm
              Send
        - else
          = link_to 'Log in', new_user_session_path
          or
          = link_to 'Register', new_user_registration_path
          to participate in the chat.
#new-message.hidden
  = render partial: 'shared/chat_message_template'

app/views/shared/_chat_message_template.html.haml
.comment.chat-entry{id: '{{messageId}}'}
  %img.portrait{:alt => "", :src => '{{userImage}}'}
    .overflow-h
      %strong
        {{username}}
      %p.chat-message {{message}}
      .chat-moderation
        - if current_user && try(:channel) && (is_channel_owner? || is_channel_moderator?)
          = link_to chat_ban_api_v1_chat_path(channel.id,'{{username}}'), id: '{{banElementId}}', class: 'ban-user', remote: true, method: :put  do
            %span.fa.fa-ban
          = link_to chat_toggle_moderator_api_v1_chat_path(channel.id, '{{username}}'), id: '{{moderatorElementId}}', class: 'toggle-moderate-user', remote: true, method: :put  do
            %span.fa.fa-star
          = link_to chat_remove_message_api_v1_chat_path(channel.id, '{{username}}', '{{messageId}}'), id: '{{removeMessageElementId}}', class: 'remove-message', remote: true, method: :delete  do
            %span.fa.fa-trash
        - else
          &nbsp;

app/views/shared/_external_stream.html.haml
.embed-content
  .embed-container
    != channel.stream_html

app/views/shared/_footer.html.haml
.footer-v1.sticky-footer
  .footer
    .container
      .row
        .col-md-6.md-margin-bottom-40
          .margin-bottom-50.margin-top-20
            = link_to image_tag('logo.png'), root_path, class: 'logo'
          %p codewatch.tv provides a platform that allows anyone to stream coding sessions for, among others, learning purposes, knowledge sharing and live tech events.
        .col-md-3.md-margin-bottom-40
          .headline
            %h2 Useful Links
          %ul.list-unstyled.link-list
            %li
              %a{:href => about_url} About
              %i.fa.fa-angle-right
            %li
              %a{:href => 'http://status.codewatch.tv', target: :blank} Service Status
              %i.fa.fa-angle-right
        .col-md-3.md-margin-bottom-40
          .headline
            %h2 Contact Us
          %address.md-margin-bottom-40
            Email:
            %a{:href => 'mailto:hi@codewatch.tv'} hi@codewatch.tv

  .copyright
    .container
      .row
        .col-md-6
          %p
            2015 &copy; All Rights Reserved.
            = link_to 'Privacy Policy', privacy_path
            |
            = link_to 'Terms of Service', terms_path
        / Social Links
        .col-md-6
          %ul.footer-socials.list-inline
            %li
              %a.tooltips{"data-original-title" => "Facebook", "data-placement" => "top", "data-toggle" => "tooltip", :href => 'https://www.facebook.com/codewatch.tv', :title => 'Facebook'}
                %i.fa.fa-facebook
            %li
              %a.tooltips{"data-original-title" => "Twitter", "data-placement" => "top", "data-toggle" => "tooltip", :href => 'https://twitter.com/codewatchtv', :title => 'Twitter'}
                %i.fa.fa-twitter

app/views/shared/_header.html.haml
.header
  .container
    = render partial: 'shared/logo'
    / Topbar
    = render partial: 'shared/topbar'
    / End Topbar
    / Toggle get grouped for better mobile display
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.fa.fa-bars
  / End Toggle
  / /end container
  / Collect the nav links, forms, and other content for toggling
  = render partial: 'shared/navigation'

app/views/shared/_logo.html.haml
= link_to image_tag('logo.png'), root_path, class: 'logo'

app/views/shared/_navigation.html.haml
.collapse.navbar-collapse.mega-menu.navbar-responsive-collapse
  .container
    %ul.nav.navbar-nav
      = navbar_item 'Home', root_path
      = navbar_item 'Browse', categories_path
      = navbar_item 'External Streams', external_channels_path
      = navbar_item 'Events', events_path
      %li
        %i.search.fa.fa-search.search-btn
        .search-open
          .input-group.animated.fadeInDown
            %input.search-activator.form-control{type: 'text', placeholder: 'Search'}

app/views/shared/_payment_logic.html.haml
= form_tag payments_path, id: 'payment-form' do
  %input{type: 'hidden', id: 'payment-type', name: 'payment[type]', value: ''}
  %input{type: 'hidden', id: 'payment-object', name: 'payment[object]', value: ''}
  %input{type: 'hidden', id: 'payment-id', name: 'payment[id]', value: ''}
  %input{type: 'hidden', id: 'payment-email', name: 'payment[email]', value: ''}
:javascript
  var handler = StripeCheckout.configure({
    key: '#{ENV['STRIPE_PUBLISHABLE_KEY']}',
    image: '#{image_path('logo.png')}',
    token: function(token) {
      $('#payment-type').val('#{payment_type}');
      $('#payment-id').val(token.id);
      $('#payment-object').val('#{payment_object}');
      $('#payment-email').val(token.email);
      $('#payment-form').submit();
    }
  });

  $('#payment-button').on('click', function(e) {
    // Open Checkout with further options
    handler.open({
      name: 'codewatch.tv',
      description: '#{payment_description}',
      currency: "usd",
      amount: #{payment_amount}
    });
    e.preventDefault();
  });

  // Close Checkout on page navigation
  $(window).on('popstate', function() {
    handler.close();
  });

app/views/shared/_private_session_stats.html.haml
#channel-stats
  .row
    - if PrivateSessionService.instance.is_not_participant?(private_session, current_user)
      #sign-up.col-sm-6.sm-margin-bottom-20
        = link_to new_private_session_payment_path(private_session.token), id: 'payment-button' do
          .service-block-v3.service-block-u
            %i.fa.fa-ticket
            %span.service-heading Sign Up
            %span.counter= private_session.price.to_i == 0 ? 'Free' : number_to_currency(private_session.price.to_f)
    - elsif private_session.max_participants.to_i > 0 && private_session.participants.count == private_session.max_participants.to_i
      #sign-up-sold-out.col-sm-6.sm-margin-bottom-20
        .service-block-v3.service-block-u
          %i.fa.fa-ticket
          %span.service-heading Sign Up
          %span.counter Sold Out :(
    - else
      #signed-up.col-sm-6.sm-margin-bottom-20
        .service-block-v3.service-block-u
          %i.fa.fa-ticket
          %span.service-heading Sign Up
          %span.counter Thank you!
    #sign-ups.col-sm-6.sm-margin-bottom-20
      .service-block-v3.service-block-yellow
        %i.fa.fa-users
        %span.service-heading Sign Ups
        - if private_session.max_participants.to_i > 0
          %span.counter= "#{private_session.participants.count}/#{private_session.max_participants}"
        - else
          %span.counter= private_session.participants.count

app/views/shared/_stream.html.haml
#stream-player
:javascript
  jwplayer("stream-player").setup({
    file: '#{file}',
    type: '#{type}',
    autostart: true,
    width: '100%',
    skin: { name: "codewatch" },
    aspectratio: '16:9',
    stretching: '#{stretching}',
    logo: { hide: true }
  });

app/views/shared/_stream_thumbnail.html.haml
%div{class: "cbp-item #{channel.user.username}"}
  .cbp-caption.margin-bottom-20
    .cbp-caption-defaultWrap
      -if channel.external? && channel.does_not_have_media?
        = link_to image_tag(channel.thumbnail), channel.url, target: :blank
      - else
        = link_to image_tag(channel.thumbnail), link
    .cbp-title-dark
      .cbp-l-grid-agency-title{title: channel.title}= channel.title
    .text-right
      %ul.list-inline.block-grid-v1-add-info
        %li
          - if channel.external?
            -if channel.status
              %a.margin-right-5{:href => channel.url, target: :blank}
                %i.fa.fa-play
                = channel.status
            %a{:href => channel.url, target: :blank}
              %i.fa.fa-user
              = channel.user.username
          - else
            %a{:href => link}
              %i.fa.fa-user
              = channel.user.username
            %a{:href => link}
              %i.fa.fa-user
              = (channel.online? ? channel.current_viewers : '0')

app/views/shared/_topbar.html.haml
.topbar
  %ul.loginbar.pull-right
    - if current_user.nil? || current_user.is_free?
      %li
        = link_to 'Upgrade to Plus!', new_plus_payment_path
      %li.topbar-devider
    %li
      = link_to 'Help', help_path
      %li.topbar-devider
    %li
      = link_to 'Blog', 'http://blog.codewatch.tv/'
      %li.topbar-devider
    - if user_signed_in?
      %li.hoverSelector
        %a
          = current_user.username
          %i.fa.fa-chevron-down
        %ul.dashboard-dropdown.hoverSelectorBlock
          %li
            = link_to 'Dashboard', user_dashboard_path
          %li
            = link_to 'My Channel', user_channel_path(current_user.username)
          %li
            = link_to 'Edit Channel', edit_user_channel_path
          %li
            = link_to 'My VoD', list_vod_path(current_user.username)
          %li
            = link_to 'Log Out', destroy_user_session_path, method: :get
    - else
      %li
        = link_to 'Login', new_user_session_path, method: :get