config/routes.rb
Codewatch::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  root to: 'home#index'

  get 'dashboard' => 'dashboard#index', as: :user_dashboard
  get 'dashboard/chat_management' => 'dashboard#chat_management', as: :user_dashboard_chat_management
  get 'dashboard/statistics' => 'dashboard#statistics', as: :user_dashboard_statistics
  get 'dashboard/stream_keys' => 'dashboard#stream_keys', as: :user_dashboard_stream_keys

  get 'dashboard/private_sessions' => 'dashboard#private_sessions', as: :user_dashboard_private_sessions
  post 'dashboard/private_sessions/create' => 'dashboard#create_private_session', as: :user_dashboard_private_sessions_create
  get 'dashboard/private_sessions/:id/edit' => 'dashboard#edit_private_session', as: :user_dashboard_private_sessions_edit
  post 'dashboard/private_sessions/:id/update' => 'dashboard#update_private_session', as: :user_dashboard_private_sessions_update
  put 'dashboard/private_sessions/:id/cancel' => 'dashboard#cancel_private_session', as: :user_dashboard_private_sessions_cancel

  get 'dashboard/subscriptions' => 'dashboard#subscriptions', as: :user_dashboard_subscriptions
  put 'dashboard/subscription/plus/:id/cancel' => 'dashboard#cancel_plus_subscription', as: :user_dashboard_plus_subscription_cancel
  put 'dashboard/subscription/channel/:id/cancel' => 'dashboard#cancel_channel_subscription', as: :user_dashboard_channel_subscription_cancel

  match 'edit/channel' => 'dashboard#edit_channel', as: :edit_user_channel, via: [ :get, :post, :delete ]

  post 'dashboard/update_user' => 'dashboard#update_user', as: :update_user
  post 'dashboard/update_settings' => 'dashboard#update_settings', as: :update_settings
  post 'dashboard/update_password' => 'dashboard#update_password', as: :update_password

  get 'dashboard/vod/delete/:id' => 'dashboard#delete_vod', as: :delete_vod
  get 'dashboard/vod/toggle_visibility/:id' => 'dashboard#show_hide_vod', as: :toggle_vod_visibility

  get 'channel/:username' => 'channel#show', as: :user_channel

  get 'categories/:category_name' => 'categories#show', as: :category_channels

  get 'categories' => 'categories#index', as: :categories

  get 'search' => 'search#search', as: :search

  get 'vod/:username' => 'vod#index', as: :list_vod
  get 'vod/:username/:recording_id' => 'vod#show', as: :show_vod

  get 'events' => 'events#index', as: :events

  get 'help' => 'help#index', as: :help

  get 'channels/external' => 'external_streams#index', as: :external_channels
  get 'channel/external/:username' => 'external_streams#show', as: :user_external_channel

  get 'private_session/:id' => 'private_sessions#show', as: :private_session

  get 'payments/plus' => 'payments#new_plus', as: :new_plus_payment
  resources :payments
  get 'payments/private-session/:id' => 'payments#new_private_session', as: :new_private_session_payment
  get 'payments/plus/success' => 'payments#plus_success', as: :plus_success_payment
  get 'payments/channel_subscription/:id' => 'payments#new_channel_subscription', as: :channel_subscription_payment
  get 'payments/channel_subscription/:id/success' => 'payments#channel_subscription_success', as: :channel_subscription_success_payment

  get 'terms' => 'terms#show', as: :terms
  get 'privacy' => 'privacy#show', as: :privacy
  get 'about' => 'about#show', as: :about

  match '404' => 'errors#error404', via: [ :get, :post, :patch, :delete ]

  post 'chat/:chat_id/new_message' => 'chat#new_message'
  namespace :api do
    namespace :v1 do
      resource :auth, defaults: {format: 'json'} do
        post 'stream' => 'auth#stream', defaults: {format: 'json'}
      end
      resource :smil, defaults: {format: 'text'} do
        get ':username' => 'smil#generate', defaults: {format: 'text'}
      end
      resource :stream, defaults: {format: 'json'} do
        post 'new_recording' => 'stream#new_recording', defaults: {format: 'json'}
        post 'event/:event' => 'stream#event', defaults: {format: 'json'}
      end
      resource :recording, defaults: {format: 'json'} do
        post 'event/:event' => 'recording#event', defaults: {format: 'json'}
      end
      resource :chat, defaults: {format: 'json'} do
        put ':channel_id/toggle_moderator/:username' => 'chat#toggle_moderator', defaults: {format: 'json'}, as: :chat_toggle_moderator
        put ':channel_id/ban/:username' => 'chat#ban', defaults: {format: 'json'}, as: :chat_ban
        put ':channel_id/unban/:username' => 'chat#unban', defaults: {format: 'json'}, as: :chat_unban
        delete ':channel_id/user/:username/delete/:message_id' => 'chat#remove_message', defaults: {format: 'json'}, as: :chat_remove_message
      end
      resource :private_session, defaults: {format: 'json'} do
        delete ':id/delete' => 'chat#toggle_moderator', defaults: {format: 'json'}, as: :delete
      end
      resource :channel, defaults: {format: 'json'} do
        post ':channel_id/like' => 'channel#like', defaults: {format: 'json'}, as: :channel_like
        delete ':channel_id/unlike' => 'channel#unlike', defaults: {format: 'json'}, as: :channel_unlike
      end
      resource :load_balancer, defaults: {format: 'json'} do
        post 'node' => 'load_balancer#stream', defaults: {format: 'json'}, as: :node
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ChannelHelper

  TOP_LANGUAGES = %w(Java C C++ C# Python JavaScript PHP Ruby Objective-C Go)

  helper_method :featured_channels
  helper_method :featured_streamers
  helper_method :top_categories
  helper_method :top_languages
  helper_method :latest_posts

  def index
  end

  private

  def top_languages
    TOP_LANGUAGES
  end

  def top_categories
    @top_categories ||= Category.in(name: TOP_LANGUAGES).inject({}) { |res, category| res[category.name] = category; res }
  end

  def featured_channels
    Channel.where(is_online: 1, :current_viewers.gt => 0).order_by(current_viewers: :desc).limit(3).to_a
  end

  def featured_streamers
    User.where(featured: 1).to_a
  end

  def latest_posts
    CW_BLOG.getPosts(filter: {number: 3, orderby: 'post_date', order: 'desc'})
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_featured_channels.html.haml
- unless featured_channels.empty?
  .container.content
    .headline
      %h2 Featured Streams
    .row.block-grid-v2
      - featured_channels.each do |channel|
        .col-md-4
          = render partial: 'shared/stream_thumbnail', locals: {classes: 'col-md-4 col-sm-6', channel: channel, link: user_channel_path(channel.user.username)}

app/views/home/_featured_streamers.html.haml
- unless featured_streamers.empty?
  .featured-streamers
    .container.margin-top-50
      .headline
        %h2 Featured Streamers
      .row.margin-top-50.margin-bottom-50
        .col-md-8.col-md-offset-2
          %ul.list-unstyled.owl-ts-v1
            - featured_streamers.each do |user|
              %li.item
                = image_tag user.gravatar_url, class: 'rounded-x img-bordered', alt: user.username
                .featured-streamers-title
                  %p= user.username
                  %span= user.occupation
                %p= user.about_me

app/views/home/_news.html.haml
.container.content
  .headline
    %h2 Latest News

  .row.service-v1.margin-bottom-40
    - latest_posts.each do |post|
      .col-md-4
        %h2= post['post_title']
        %p= post['post_excerpt']
        %p
          %a{href: post['link'], target: :blank} See more...

app/views/home/_search.html.haml
.search-block
  .container
    .col-md-6.col-md-offset-3
      %h1
        Explore
        %span.color-green CodeWatch
      .input-group
        %input.search-activator.form-control{:placeholder => "Search ...", :type => "text"}
          %span.input-group-btn
            %button.btn-u.btn-u-lg{:type => "button"}
              %i.fa.fa-search
    .col-md-6.col-md-offset-3.margin-top-50
      %a#create_new_account.btn-u.btn-u-lg.text-center{href: new_registration_path(User)} Create new account

app/views/home/_stats.html.haml
.parallax-counter-v2
  .container
    %ul.row.list-row
      %li.col-md-3.col-sm-6.col-xs-12.md-margin-bottom-30
        .counters.rounded
          %span.counter 18298
          %h4 Online Streams
      %li.col-md-3.col-sm-6.col-xs-12.md-margin-bottom-30
        .counters.rounded
          %span.counter 24583
          %h4 Online Users
      %li.col-md-3.col-sm-6.col-xs-12.sm-margin-bottom-30
        .counters.rounded
          %span.counter 37904
          %h4 Monthly Users
      %li.col-md-3.col-sm-6.col-xs-12
        .counters.rounded
          %span.counter 50892
          %h4 Hours Streamed

app/views/home/_top_categories.html.haml
.bg-highlighted
  .container.content
    .headline
      %h2 Top Categories
    .row.category.margin-bottom-20
      - top_languages.each_slice(5).to_a.each do |category_slice|
        .col-md-6.col-sm-8
          - category_slice.each do |category_name, description|
            .content-boxes-v3.margin-bottom-10.md-margin-bottom-20
              %i.icon-custom.icon-sm.rounded-x.icon-bg-sea.icon-line.fa.fa-code
              .content-boxes-in-v3
                %h3
                  = link_to top_categories[category_name].name, category_channels_path(top_categories[category_name].name)
                %p= top_categories[category_name].description

app/views/home/_welcome.html.haml
.container.content.margin-top-50
  .row
    .col-md-4
      .title-box
        .title-box-text
          Coding
          %span.color-green Sessions
        %p
          Thousands of hours of live and recorded coding sessions
    .col-md-4
      .title-box
        .title-box-text
          Knowledge
          %span.color-green Sharing
        %p
          Nothing beats being able to watch live coding sessions and be able to interact with the coder in real time
    .col-md-4
      .title-box
        .title-box-text
          Tech
          %span.color-green Events
        %p
          Watch live conferences and tech events, right here in your browser
  .row.margin-top-50.margin-bottom-50
    .col-md-2.col-md-offset-4
      .left
        = button_to 'https://www.facebook.com/codewatch.tv', {class: 'btn btn-block btn-facebook-inversed rounded', method: :get} do
          %i.fa.fa-facebook
          Facebook
    .col-md-2
      .left
        = button_to 'https://twitter.com/codewatchtv', {class: 'btn btn-block btn-twitter-inversed rounded', method: :get} do
          %i.fa.fa-twitter
          Twitter

app/views/home/index.html.haml
#home-search
  = render partial: 'home/search'
#welcome
  = render partial: 'home/welcome'
#home-featured-channels
  = render partial: 'home/featured_channels'
#home-top-categories
  = render partial: 'home/top_categories'
#home-featured-streamers
  = render partial: 'home/featured_streamers'
#home-news
  = render partial: 'home/news'
#home-stats
  -#= render partial: 'home/stats'